services:
  myweb:
    image: jooheee111/infra-web:1.0
    container_name: myweb
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - web-html:/var/www/html
      - web-logs:/var/log/httpd
    networks:
      infra-net:
        ipv4_address: 172.30.0.20
    depends_on:
      mynfs:
        condition: service_healthy
    restart: unless-stopped

  mynfs:
    image: jooheee111/infra-nfs:1.0
    container_name: mynfs
    privileged: true
    ports:
      - "2049:2049"
    volumes:
      - nfs-data:/exports
    networks:
      infra-net:
        ipv4_address: 172.30.0.50
    healthcheck:
      test: ["CMD", "showmount", "-e", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

networks:
  infra-net:
    name: infra-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

volumes:
  web-html:
  nfs-data:
  web-logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.30.0.50,rw,nolock,soft
      device: ":/exports"